### ISSUE TITLE
internal compiler error in c_binding.f90

### ISSUE THREAD

**Issue by Mattiads1** [LadaF/PoisFFT#12]
Hi, I already compiled and used the library on my personal computer, and it works very well!!
But when I try to compile the library on another computer (I'm not the administrator) I get 
f951: internal compiler error: Segmentation fault, when gfortran try to compile c_binding.f90.
The version of gfortran is GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28).

What do I need to solve this problem?

**Comment by LadaF** [comment]
You will likely need a more recent compiler. Every "internal compiler
error" is exactly what it says, an internal error in the compiler. I used
to do a lot of testing on 4.8 so I am a bit surprised there is a problem
there but I no longer have a computer with this very old version and I no
longer support it.

  Vladimir

**Comment by Mattiads1** [comment]
Then, there is no way to solve the problem?

**Comment by LadaF** [comment]
You could remove the C and C++ parts from the compilation if you do not use
them. Just comment out the relevant lines in SConstruct.

**Comment by Mattiads1** [comment]
Which are the relevant lines in SConstruct?
I'm not good with SConstruct

**Comment by LadaF** [comment]
In that case it will be best to upgrade your compiler. 4.8 is old and not supported any more.

**Comment by Mattiads1** [comment]
I tried to compile the library with ifort, version 17.0.4 20170411, and now I get this error:

./poisfft-inc.f90(45): error #6406: Conflicting attributes or multiple declaration of name.   [POISFFT_SOLVER3D]
  interface PoisFFT_Solver3D
------------^
./poisfft-inc.f90(45): error #6406: Conflicting attributes or multiple declaration of name.   [POISFFT_SOLVER3D]
  interface PoisFFT_Solver3D
------------^

Unfortunately, I'm not the administrator of the computer where I want to compile the library, and I cannot upgrade the compilers. 
On my laptop, I have ifort version 19.1.1.217 20200306 and it works perfectly.

**Comment by LadaF** [comment]
You do not need to be an admin to install a compiler. You can install it in
your user profile. Best by compiling the GCC source code. I did that many
times.

**Comment by LadaF** [comment]
Or you can try to install pre-compiled binaries from
http://gfortran.meteodat.ch/download/x86_64 See the readme first.
