### ISSUE TITLE
How to use PoisFFT from Visual Studio

### ISSUE THREAD

**Issue by hamiderfani** [LadaF/PoisFFT#6]
dear LadaF;
I want to solve a hydrological problem using your solver in 2D and 3D. I have a problem compiling the files in windows visual studio for FORTRAN; Can you please help me in this regard? 

Many thanks in advance

**Comment by LadaF** [comment]
Hi, I do not use Visual Studio. Note that Visual Studio is not a Fortran Compiler, it is just an editor and a build system. The steps may differ between different Compilers. Are you using Intel Visual Fortran or some other Fortran compiler?

I suggest to compile PoisFFT using `scons` by calling the appropriate compiler in the command line (probably it is `ifort`). Then you can find out how to link it from Visual Studio.
