### ISSUE TITLE
 installation problems using GNU  compilers

### ISSUE THREAD

**Issue by ClarkGuilty** [LadaF/PoisFFT#7]
Hello, I have installed your library in Ubuntu 18.04 and Manjaro using the GNU compilers, however, the line 137 of the SConstruct file (env.Append(FORTRANMODDIRPREFIX = '-J') ) seems to be unnecessary now and harms the install process.

I simply commented the line and the installation proceed flawlessly.

**Comment by LadaF** [comment]
I have noticed this behaviour with some very recent version of scons.
However, my Linux distro still does not have it. I would need some if
condition to disable the option for the new version. If you know how to do
it, feel free to comment.

Dne so 5. 10. 2019 20:48 uživatel Javier Alejandro Acevedo Barroso <
notifications@github.com> napsal:

**Comment by LadaF** [comment]
This was fixed some time ago, closing the issue.
